#!/usr/bin/env bash
set -euo pipefail

# Usage: ./generate-env.sh <instance-name>
# Creates .env.<instance-name> with generated secrets and auto-assigned ports.
# Port assignments are tracked in .ports (gitignored).

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  echo "Usage: $0 <instance-name> [host]"
  echo ""
  echo "Creates .env.<instance-name> with generated secrets and auto-assigned ports."
  echo ""
  echo "  host   IP or domain of the host running the stack (default: prompt)"
  echo "         Used for SUPABASE_PUBLIC_URL and API_EXTERNAL_URL."
  echo ""
  echo "Port slots are tracked in .ports (gitignored). Each new instance gets the"
  echo "next available slot, offsetting all ports by 1:"
  echo "  Slot 0: Kong=8000, HTTPS=8443, Postgres=5432, Pooler=6543"
  echo "  Slot 1: Kong=8001, HTTPS=8444, Postgres=5433, Pooler=6544"
  echo "  ..."
  echo ""
  echo "Examples:"
  echo "  $0 homelab 192.168.1.50"
  echo "  $0 prod supabase.example.com"
  exit 0
fi

command -v openssl >/dev/null || { echo "openssl required"; exit 1; }
command -v node    >/dev/null || { echo "node required (for JWT generation)"; exit 1; }

NAME="${1:-}"
if [ -z "$NAME" ]; then
  read -rp "Instance name (e.g. homelab, prod): " NAME
fi
if [ -z "$NAME" ]; then
  echo "Instance name required."
  exit 1
fi
OUTFILE=".env.${NAME}"

HOST="${2:-}"
if [ -z "$HOST" ]; then
  read -rp "Host IP or domain for this instance (e.g. 192.168.1.50 or supabase.example.com): " HOST
fi
if [ -z "$HOST" ]; then
  HOST="localhost"
fi
PORTS_FILE=".ports"

if [ -f "$OUTFILE" ]; then
  echo "ERROR: $OUTFILE already exists. Delete it first or choose a different name."
  exit 1
fi

# Assign port slot — each slot offsets all ports by 1
# Slot 0: http=8000, https=8443, postgres=5432, pooler=6543
# Slot 1: http=8001, https=8444, postgres=5433, pooler=6544
# etc.
if [ -f "$PORTS_FILE" ] && grep -q "^${NAME}=" "$PORTS_FILE" 2>/dev/null; then
  SLOT=$(grep "^${NAME}=" "$PORTS_FILE" | cut -d= -f2)
  echo "Reusing existing port slot ${SLOT} for instance: $NAME"
else
  if [ -f "$PORTS_FILE" ]; then
    MAX_SLOT=$(grep -v '^#' "$PORTS_FILE" | grep '=' | cut -d= -f2 | sort -n | tail -1)
    SLOT=$(( ${MAX_SLOT:-0} + 1 ))
  else
    SLOT=0
  fi
  echo "${NAME}=${SLOT}" >> "$PORTS_FILE"
  echo "Assigned port slot ${SLOT} to instance: $NAME"
fi

KONG_HTTP_PORT=$(( 8000 + SLOT ))
KONG_HTTPS_PORT=$(( 8443 + SLOT ))
POSTGRES_PORT=$(( 5432 + SLOT ))
POOLER_PORT=$(( 6543 + SLOT ))

echo "  Kong HTTP:  ${KONG_HTTP_PORT}"
echo "  Kong HTTPS: ${KONG_HTTPS_PORT}"
echo "  Postgres:   ${POSTGRES_PORT}"
echo "  Pooler:     ${POOLER_PORT}"
echo ""
echo "Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '\n=+/')
JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n=')
SECRET_KEY_BASE=$(openssl rand -base64 64 | tr -d '\n=')
VAULT_ENC_KEY=$(openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-32)
PG_META_CRYPTO_KEY=$(openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-32)
LOGFLARE_PUBLIC=$(openssl rand -hex 32)
LOGFLARE_PRIVATE=$(openssl rand -hex 32)
S3_KEY_ID=$(openssl rand -hex 16)
S3_KEY_SECRET=$(openssl rand -hex 32)
DASHBOARD_PASSWORD=$(openssl rand -base64 20 | tr -d '\n=+/')

JWT_KEYS=$(JWT_SECRET="$JWT_SECRET" NOW=$(date +%s) EXP=2556143999 node -e '
const crypto = require("crypto");
const secret = process.env.JWT_SECRET;
const now = parseInt(process.env.NOW);
const exp = parseInt(process.env.EXP);
function b64u(s) { return Buffer.from(s).toString("base64").replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_"); }
function jwt(payload) {
  const h = b64u(JSON.stringify({alg:"HS256",typ:"JWT"}));
  const p = b64u(JSON.stringify(payload));
  const s = crypto.createHmac("sha256",secret).update(h+"."+p).digest("base64").replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_");
  return h+"."+p+"."+s;
}
console.log(jwt({role:"anon",iss:"supabase",iat:now,exp:exp}));
console.log(jwt({role:"service_role",iss:"supabase",iat:now,exp:exp}));
')
ANON_KEY=$(echo "$JWT_KEYS" | head -1)
SERVICE_ROLE_KEY=$(echo "$JWT_KEYS" | tail -1)

cat > "$OUTFILE" << EOF
############
# Secrets — generated by generate-env.sh, do not commit
############

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

SUPABASE_PUBLISHABLE_KEY=
SUPABASE_SECRET_KEY=
JWT_KEYS=
JWT_JWKS=
ANON_KEY_ASYMMETRIC=
SERVICE_ROLE_KEY_ASYMMETRIC=

DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}

SECRET_KEY_BASE=${SECRET_KEY_BASE}
VAULT_ENC_KEY=${VAULT_ENC_KEY}
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}

LOGFLARE_PUBLIC_ACCESS_TOKEN=${LOGFLARE_PUBLIC}
LOGFLARE_PRIVATE_ACCESS_TOKEN=${LOGFLARE_PRIVATE}

S3_PROTOCOL_ACCESS_KEY_ID=${S3_KEY_ID}
S3_PROTOCOL_ACCESS_KEY_SECRET=${S3_KEY_SECRET}


############
# URLs — EDIT THESE before deploying
############

SUPABASE_PUBLIC_URL=http://${HOST}:${KONG_HTTP_PORT}
API_EXTERNAL_URL=http://${HOST}:${KONG_HTTP_PORT}
SITE_URL=http://${HOST}:3000


############
# Database
############

POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=${POSTGRES_PORT}


############
# Supavisor
############

POOLER_PROXY_PORT_TRANSACTION=${POOLER_PORT}
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_DB_POOL_SIZE=5
POOLER_TENANT_ID=${NAME}


############
# Studio
############

STUDIO_DEFAULT_ORGANIZATION=${NAME}
STUDIO_DEFAULT_PROJECT=Default Project
OPENAI_API_KEY=


############
# Auth
############

ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false

MAILER_URLPATHS_CONFIRMATION="/auth/v1/verify"
MAILER_URLPATHS_INVITE="/auth/v1/verify"
MAILER_URLPATHS_RECOVERY="/auth/v1/verify"
MAILER_URLPATHS_EMAIL_CHANGE="/auth/v1/verify"

ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
ENABLE_ANONYMOUS_USERS=false

# SMTP — fill in to enable email auth (password reset, invites, etc.)
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_SENDER_NAME=Supabase

ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false


############
# Storage
############

GLOBAL_S3_BUCKET=stub
REGION=stub
STORAGE_TENANT_ID=stub


############
# Edge Functions
############

FUNCTIONS_VERIFY_JWT=false


############
# API / PostgREST
############

PGRST_DB_SCHEMAS=public,storage,graphql_public
PGRST_DB_MAX_ROWS=1000
PGRST_DB_EXTRA_SEARCH_PATH=public


############
# Analytics / Vector
############

DOCKER_SOCKET_LOCATION=/var/run/docker.sock
GOOGLE_PROJECT_ID=
GOOGLE_PROJECT_NUMBER=


############
# Ports — slot ${SLOT}, managed by .ports registry
############

KONG_HTTP_PORT=${KONG_HTTP_PORT}
KONG_HTTPS_PORT=${KONG_HTTPS_PORT}


############
# imgproxy
############

IMGPROXY_AUTO_WEBP=true
EOF

echo "Created: $OUTFILE"
echo ""
echo "Dashboard login: supabase / ${DASHBOARD_PASSWORD}"
echo "Studio URL:      http://${HOST}:${KONG_HTTP_PORT}"
